### ISSUE TITLE
播放rtsp流时，需要等待几秒才可以播放，无法做到秒播放

### ISSUE THREAD

**Issue by hydaizd** [Monibuca/plugin-rtsp#34]
在播放rtsp时，如果以下配置设置为true时，需要等待几秒才开始播放录像：
```yaml
rtsp:
  publish:
    pubaudio: true
  subscribe:
    subaudio: true
```
如果将此值都设置为false，则速度明显提高，几乎可以做到秒播放，想问下这个地方有没有什么优化方案？
